### ISSUE TITLE
Create conda recipe

### ISSUE THREAD

**Issue by fcollonval** [hadim/jupyter-archive#26]
@hadim I would like to create a conda recipe on conda-forge. Is it ok for you? Do you want to be added as maintainer?

FYI - recipe template
```yml
{% set name = "jupyter-archive" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c578affa23afcfebb1b2a7956db46f48dc6477cf804f8af8a1be638ffa039ac9
  
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"


requirements:
  host:
    - python >=3.5
    - pip
  build:
    - nodejs
  run:
    - python >=3.5
    - jupyterlab >=1
test:
  imports:
    - jupyter_archive

about:
  home: https://github.com/hadim/jupyter-archive
  summary: Make, download and extract archive files in Jupyter.
  description: Make, download and extract archive files in Jupyter.
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - fcollonval
```
